Add Clang support (#7)
* fix warning Wno-undefined-optimized

* fix undefined reference to 'stpcpy'

* disable CONFIG_CRYPTO_FIPS

* Fix GCC_TOOLCHAIN_DIR prefix for Clang cross compilation

* Nuke mstdrv

* Remove GCC wrapper

* build: fix clang support
The kernel compiles with clang, but doesn't boot because of memory
unalignment. To fix this, force all objects to be aligned.